# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170711_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
