# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_habit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='checked_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
