# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170712_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='checked_date',
            field=models.DateField(default=datetime.date.today, verbose_name='CheckDate'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='StartDate'),
        ),
    ]
