# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170712_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='checked_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
