# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20170623_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text_tag',
            field=models.TextField(default='tag'),
        ),
    ]
