# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_note_text_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text_tag',
            field=models.TextField(blank=True, default='tag'),
        ),
    ]
