# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_auto_20170623_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text_tag',
            field=models.CharField(blank=True, default='tag', max_length=500),
        ),
    ]
